"""
Django settings for the ShopHub project (config).

Generated by 'django-admin startproject', then heavily customized for a
pure-backend, interview-ready API using Django REST Framework.

Learning notes on WHY each section is here:
  * AUTH_USER_MODEL      : we use a CUSTOM User (users.User) instead of Django's
    default. This is best practice because swapping it after first migration is
    painful. It also lets us add fields (e.g. `bio`) later.
  * DATABASES            : points at our local Postgres 'shophub' DB.
  * REST_FRAMEWORK       : configures DRF auth classes (JWT), default permissions,
    pagination, and filtering backends.
  * CACHES + CELERY      : share the local Redis (same container as the other two
    projects) for caching and as the Celery broker.
  * drf-spectacular      : auto-generates OpenAPI docs at /api/schema/ + /api/docs/.

Values come from a .env file (via python-dotenv) OR defaults defined here, so the
project runs out-of-the-box but is configurable for other environments.
"""

from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Load configuration from the .env file at the project root (git-ignored).
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

import os  # noqa: E402  (imported after load_dotenv for clarity)

# ---------------------------------------------------------------------------
# SECURITY
# ---------------------------------------------------------------------------
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-dev-change-me")
DEBUG = os.getenv("DEBUG", "true").lower() == "true"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# ---------------------------------------------------------------------------
# APPS
# ---------------------------------------------------------------------------
INSTALLED_APPS = [
    # --- Django built-ins ------------------------------------------------
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # --- Third-party ------------------------------------------------------
    "rest_framework",                 # DRF core
    "rest_framework_simplejwt",       # JWT auth scheme
    "corsheaders",                    # CORS for browser front-ends
    "django_celery_beat",             # periodic tasks via admin
    "drf_spectacular",                # OpenAPI schema + docs UI

    # --- Our apps (pure backend) -----------------------------------------
    "users",
    "products",
    "orders",
    "files",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # must be high in the list
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

# Template engine config. Required because the Django ADMIN app renders HTML
# (contacts, login screen, etc.). Our public API is pure JSON via DRF, but we
# keep the admin tool for operations, so the template backend must be present.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,                     # find templates inside each app
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ---------------------------------------------------------------------------
# CUSTOM USER MODEL  (interview topic: never use the default in new projects)
# ---------------------------------------------------------------------------
AUTH_USER_MODEL = "users.User"

# ---------------------------------------------------------------------------
# DATABASE (Postgres)
# ---------------------------------------------------------------------------
# Same pattern as the other projects: user `shophub` on the local Postgres.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "shophub"),
        "USER": os.getenv("POSTGRES_USER", "shophub"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "shophub"),
        "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# ---------------------------------------------------------------------------
# AUTH / PASSWORDS
# ---------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ---------------------------------------------------------------------------
# DRF  (the heart of the API)
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # JWT via simplejwt -> `Authorization: Bearer <token>`
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # optional: admin session auth so the browsable API works locally
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        # default: must be authenticated. Per-view overrides relax this.
        "rest_framework.permissions.IsAuthenticated",
    ),
    # Built-in DRF pagination: ?page=1&page_size=10
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    # Simple filtering (?category=...), plus search/ordering shown per-view.
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
    ),
    # OpenAPI schema generator
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# simplejwt settings: lifetime of the access/refresh tokens.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,   # issue a new refresh token on refresh
    "BLACKLIST_AFTER_ROTATION": True,
}

# ---------------------------------------------------------------------------
# PAGINATION default (fallback if DRF's own is replaced)
# ---------------------------------------------------------------------------
# (DRF's PageNumberPagination above is used; this section left for reference.)

# ---------------------------------------------------------------------------
# CACHING (Redis)
# ---------------------------------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
    }
}
# Example of using the cache in code:  cache.set(key, val, 60) / cache.get(key)

# ---------------------------------------------------------------------------
# CELERY (background tasks) -- broker = Redis
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/2")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# ---------------------------------------------------------------------------
# CORS (for browser front-ends hitting this API from another origin)
# ---------------------------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True  # restrict to real domains in production
# When using JWT in the Authorization header, allow these:
CORS_ALLOW_HEADERS = ["*"]

# ---------------------------------------------------------------------------
# INTERNATIONALIZATION
# ---------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ---------------------------------------------------------------------------
# STATIC / MEDIA
# ---------------------------------------------------------------------------
STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ---------------------------------------------------------------------------
# DEFAULT PRIMARY KEY TYPE
# ---------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# SPECTACULAR (OpenAPI docs) config
# ---------------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    "TITLE": "ShopHub API",
    "DESCRIPTION": "Django + DRF interview-prep shop API (basic -> advanced)",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}
